// BattleScout.js - a battle node's foes, read before the party walks in (docs/specs/blessings-v3.md
// §6.6, decision D-21): Thief's Lantern shows which foes carry items, Seer's Eye every foe with its
// affixes and what it carries (`route_scout`, EarnedBoons.routeScoutOf).
//
// THE SCOUT NEVER LOCKS THE NODE. A locked node keeps its map and is exempt from the Eclipse's
// falls (EclipseSystem.nodeFallExemption 'locked'), so a scout that locked what it showed would
// change the Eclipse for every holder. Instead a node not yet locked is generated here exactly as
// the battle will generate it, from the same inputs, and nothing is kept but an in-memory copy:
//   - the params are the run's (`RunManager.getBattleParams(node)`) with the two fields the battle
//     adds as it begins (`applyGenerationFields`: how many units deploy, and whether it is the
//     boss's), the deploy count being the deploy screen's (`scoutDeployCount`: the roster, up to
//     the act's cap with its bonus, or the lock's spawns);
//   - the seed is the battle's (`battleGenerationSeed`: the node's `battleSeed`), and the map is
//     generated by the battle's own call (`generateSeededBattle`), which swaps Math.random for a
//     stream of that seed and puts it back, so no stream the run or the battle reads moves.
// BattleScene.beginBattle calls the same three functions (tests/BattleScout.test.js holds the
// scene to them), so at the same inputs the scout and the battle are one map. What can still
// differ is the inputs: the player deploying fewer units than the scout assumed (the line says
// "Scouted for N in the field"), or the run changing before the party arrives (the Eclipse's
// phase, a burden). A LOCKED node is read, never generated: its map is set.
//
// Nothing is written to the run: the params are a copy (generation writes a recruit's name to the
// run's used-name ledger, which the params share), and the map is never locked. The one thing a
// scout may do early is what getBattleParams does at every battle's entry: the roster's idempotent,
// stream-free preparation (duplicate names repaired and tracked, uids, portrait variants).
// No Phaser, no DOM.

import { generateBattle } from './MapGenerator.js';
import { createSeededRng } from './BlessingEngine.js';
import { resolveDeployLimits } from './BattleDeployCount.js';
import { routeScoutOf, ROUTE_SCOUT_LEVELS } from './EarnedBoons.js';
import { isPrologueRun } from './ScriptedBattle.js';
import { DEPLOY_LIMITS } from '../utils/constants.js';

/** The node types a scout reads (an event's fight is picked on arrival; a service is no battle). */
export const SCOUTED_NODE_TYPES = Object.freeze(['battle', 'boss', 'recruit']);

/**
 * The fields a battle adds to its params as it begins, before its map is generated: how many
 * units it deploys (MapGenerator sizes spawns and foes by it) and whether it is the act's boss.
 * Mutates `params` and returns it. BattleScene.beginBattle and the scout both call it.
 * @param {object} params
 * @param {{ deployCount: number, isBoss?: boolean }} fields
 */
export function applyGenerationFields(params, { deployCount, isBoss = false }) {
  params.deployCount = deployCount;
  params.isBoss = Boolean(isBoss);
  return params;
}

/**
 * The fallback battle seed of a node with no `battleSeed` of its own: FNV-1a of
 * "<run seed>:<node key>" (BattleScene.deriveBattleSeed's rule; the key is the node id, else
 * the act).
 */
export function deriveNodeBattleSeed(runSeed, nodeKey) {
  const input = `${Number(runSeed || 0) >>> 0}:${String(nodeKey)}`;
  let h = 2166136261 >>> 0;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** The seed a battle's map is generated from: its params' `battleSeed`, else the derived one. */
export function battleGenerationSeed(params, { runSeed = 0, nodeId = null } = {}) {
  if (Number.isFinite(params?.battleSeed)) return params.battleSeed;
  return deriveNodeBattleSeed(runSeed, nodeId || params?.act || 'battle');
}

/**
 * Generate a battle's map from `seed`: Math.random is a stream of that seed for the generation
 * only, and whatever it was before is put back, even on a throw.
 */
export function generateSeededBattle(params, gameData, seed) {
  const previous = Math.random;
  Math.random = createSeededRng(Number(seed) >>> 0);
  try {
    return generateBattle(params, gameData);
  } finally {
    Math.random = previous;
  }
}

/**
 * The deploy count a scout assumes: the deploy screen's (BattleScene.create): the whole roster
 * when it fits, else the act's cap with the run's deploy bonus, never more than a locked map's
 * spawns.
 */
export function scoutDeployCount(run, node) {
  const act = node?.battleParams?.act || run?.currentAct || 'act1';
  const { max } = resolveDeployLimits({
    base: DEPLOY_LIMITS[act] || DEPLOY_LIMITS.act1,
    deployBonus: run?.getDeployBonus?.() || 0,
    lockedSpawnCount: run?.getLockedSpawnCount?.(node?.id) ?? null,
  });
  const roster = Array.isArray(run?.roster) ? run.roster.length : 0;
  return Math.max(1, Math.min(roster || max, max));
}

/** What a scout shows of one spawn: who, how strong, its affixes and what it carries. */
function foeOf(spawn) {
  return {
    className: String(spawn?.className || ''),
    level: Math.max(1, Math.trunc(Number(spawn?.level) || 1)),
    isBoss: spawn?.isBoss === true,
    affixes: Array.isArray(spawn?.affixes)
      ? spawn.affixes.filter((a) => typeof a === 'string')
      : [],
    carries: typeof spawn?.carries === 'string' && spawn.carries ? spawn.carries : null,
  };
}

// In memory only (never saved): node id -> { key, scout } per run. The key is everything the map
// is generated from, so a change before arrival (the Eclipse's phase, a burden, the roster's size)
// is a fresh scout, and a repeat look is free.
const cache = new WeakMap();

function cached(run, nodeId, key, build) {
  let byNode = cache.get(run);
  if (!byNode) cache.set(run, (byNode = new Map()));
  const hit = byNode.get(nodeId);
  if (hit && hit.key === key) return hit.scout;
  const scout = build();
  byNode.set(nodeId, { key, scout });
  return scout;
}

/** True when `node` is a battle the run's scout may read (a battle type, not walked, not authored). */
export function isScoutableNode(run, node) {
  if (!run || !node || isPrologueRun(run)) return false;
  if (!SCOUTED_NODE_TYPES.includes(node.type) || !node.battleParams) return false;
  return node.completed !== true;
}

/**
 * The foes waiting at `node`, as the run's scout shows them, or null (no scout held, a node it
 * does not read, or a map that could not be built). `level` is the scout's rung name
 * ('carriers' | 'foes'); `locked` says the map is set (read, not generated); `deployCount` is
 * the deploy the foes were sized for. Never locks the node and never moves a stream.
 * @param {object} run - RunManager
 * @param {object} node
 * @returns {{ nodeId: string, level: string, locked: boolean, deployCount: number,
 *   foes: Array<{ className: string, level: number, isBoss: boolean, affixes: string[],
 *   carries: string|null }> }|null}
 */
export function scoutBattle(run, node) {
  const rank = routeScoutOf(run);
  if (rank <= 0 || !isScoutableNode(run, node)) return null;
  const level = ROUTE_SCOUT_LEVELS[rank - 1];
  // Thief's Lantern shows the carriers alone (who, how strong, what), never the rest of the field.
  const shown = (foes) =>
    level === 'foes'
      ? foes.map((f) => ({ ...f, affixes: [...f.affixes] }))
      : foes.filter((f) => f.carries).map((f) => ({ ...f, affixes: [] }));
  // A locked map is read as stored (read-only: nothing is reconciled or written here).
  const locked = run.battleConfigsByNodeId?.[node.id] || null;
  if (locked) {
    const spawns = Array.isArray(locked.enemySpawns) ? locked.enemySpawns : [];
    return {
      nodeId: node.id,
      level,
      locked: true,
      deployCount: Array.isArray(locked.playerSpawns) ? locked.playerSpawns.length : 0,
      foes: shown(spawns.map(foeOf)),
    };
  }
  try {
    // A copy: the params hold the run's own used-name ledger, which a recruit battle's
    // generation writes to (the recruit's name). The scout's copy keeps that write to itself.
    const params = structuredClone(run.getBattleParams(node));
    if (!params) return null;
    const deployCount = scoutDeployCount(run, node);
    applyGenerationFields(params, { deployCount, isBoss: node.type === 'boss' });
    const seed = battleGenerationSeed(params, { runSeed: run.runSeed, nodeId: node.id });
    const key = `${seed}|${JSON.stringify(params)}`;
    const foes = cached(run, node.id, key, () =>
      (generateSeededBattle(params, run.gameData, seed).enemySpawns || []).map(foeOf),
    );
    return { nodeId: node.id, level, locked: false, deployCount, foes: shown(foes) };
  } catch (err) {
    console.warn('[BattleScout] could not scout', node?.id, err);
    return null;
  }
}
