// SanctumPass.js — the Old Sanctum (docs/specs/blessings-v3.md §6.3, decision D-5).
// Pure: no Phaser, no Math.random, no RunManager.
//
// From the run's second act, each act's route map may hold one Old Sanctum: an ordinary church
// whose vow offers an earned blessing (engine/EarnedBlessings.js `openSanctum`, ChurchVow). The
// map is generated by NodeMapGenerator from the node-map stream, which this pass never touches:
// it runs afterwards (RunManager.advanceAct, after Pilgrim's Road's shops) on its OWN keyed
// stream, a hash of the run seed and the act. Two draws: the first is the chance (always spent),
// the second picks one of the act's churches that are not complete and not taken by the Eclipse,
// sorted by id. The node gains `sanctum: true` and the map `sanctumRolled: true`, so a second
// call (or a reload) never stamps another. Never in the first act, the final boss's act or the
// prologue (the caller's checks), and never on load: a save from before sanctums gets one from
// its next act. A sanctum can still fall to the Eclipse like any church (it is then a battle).

import { NODE_TYPES } from '../utils/constants.js';
import { createSeededRng } from './BlessingEngine.js';
import { eclipseHash } from './EclipseSystem.js';

/** True for a node that is an Old Sanctum now: a church stamped so, not taken by the Eclipse. */
export function isSanctum(node) {
  return node?.type === NODE_TYPES.CHURCH && node.sanctum === true && !node.eclipse;
}

/** The churches the pass may stamp, sorted by id. */
export function sanctumCandidates(nodeMap) {
  return (nodeMap?.nodes || [])
    .filter(
      (node) =>
        node?.type === NODE_TYPES.CHURCH &&
        node.completed !== true &&
        !node.eclipse &&
        node.darkOmen !== true,
    )
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

/**
 * Stamp this act's Old Sanctum, in place: returns the stamped node's id, or null (the chance
 * missed, no church stood, the map was already rolled, or the act takes none).
 * @param {object} nodeMap - { actId, nodes }
 * @param {{ runSeed: number, actIndex: number, chance: number }} options
 */
export function stampSanctum(nodeMap, { runSeed, actIndex, chance } = {}) {
  if (!nodeMap || !Array.isArray(nodeMap.nodes) || nodeMap.sanctumRolled === true) return null;
  if (!(Math.trunc(Number(actIndex)) >= 1) || nodeMap.actId === 'finalBoss') return null;
  nodeMap.sanctumRolled = true;
  const rng = createSeededRng(eclipseHash(`sanctum:${Number(runSeed) >>> 0}:${nodeMap.actId}`));
  const hit = rng() < (Number(chance) || 0);
  const roll = rng();
  if (!hit) return null;
  const candidates = sanctumCandidates(nodeMap);
  if (candidates.length === 0) return null;
  const pick = candidates[Math.min(candidates.length - 1, Math.floor(roll * candidates.length))];
  pick.sanctum = true;
  return pick.id;
}
