#!/usr/bin/env python3
"""Render compositions in tools/music/scores/ to game-ready loops.

  python3 tools/music/build.py battle_border            # render one score
  python3 tools/music/build.py --all                    # render everything
  python3 tools/music/build.py battle_border --preview  # also write jump previews

Outputs go to assets/audio/music/<key>.mp3 (+ <key>_<variant>.mp3) and the
loop table src/utils/musicLoops.js is rewritten from tools/music/loops.json.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from engine.render import Renderer  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'assets', 'audio', 'music')
PREVIEW = os.path.join(ROOT, 'References', 'music-preview')
LOOPS_JSON = os.path.join(HERE, 'loops.json')
LOOPS_JS = os.path.join(ROOT, 'src', 'utils', 'musicLoops.js')


def list_scores():
    return sorted(f[:-3] for f in os.listdir(os.path.join(HERE, 'scores'))
                  if f.endswith('.py') and not f.startswith('_'))


def write_loops_js(table):
    lines = [
        '// Generated by tools/music/build.py from tools/music/loops.json. Do not edit.',
        '// Loop points (seconds) for the composed score: each file plays its intro once,',
        '// then loops [loopStart, loopEnd). Variants of one cue share identical timing so',
        '// the adaptive layers can crossfade sample-accurately. `duration` lets the',
        '// player reject loop points that do not belong to the decoded file.',
        'export const MUSIC_LOOPS = {',
    ]
    for key in sorted(table):
        e = table[key]
        lines.append(f"  {key}: {{ loopStart: {e['loopStart']}, loopEnd: {e['loopEnd']}, "
                     f"duration: {e['duration']} }},")
    lines.append('};')
    lines.append('')
    with open(LOOPS_JS, 'w') as f:
        f.write('\n'.join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scores', nargs='*')
    ap.add_argument('--all', action='store_true')
    ap.add_argument('--preview', action='store_true')
    ap.add_argument('--no-out', action='store_true', help='skip writing game assets')
    ap.add_argument('--variants', nargs='*')
    args = ap.parse_args()
    names = list_scores() if args.all else args.scores
    table = json.load(open(LOOPS_JSON)) if os.path.exists(LOOPS_JSON) else {}
    for name in names:
        t = time.time()
        mod = importlib.import_module(f'scores.{name}')
        score = mod.build()
        key = getattr(mod, 'KEY', f'music_{name}')
        print(f'[{name}] -> {key}  ({score.title})')
        r = Renderer(score)
        meta = r.export(key, variants=args.variants, out_dir=None if args.no_out else OUT,
                        preview_dir=PREVIEW if args.preview else None)
        if not args.no_out:
            for k, info in meta.items():
                table[k] = {**info, 'score': name, 'title': score.title}
        print(f'[{name}] done in {time.time() - t:.1f}s')
    if not args.no_out:
        with open(LOOPS_JSON, 'w') as f:
            json.dump(table, f, indent=1, sort_keys=True)
        write_loops_js(table)


if __name__ == '__main__':
    main()
