#!/usr/bin/env python3
"""Render compositions in tools/music/scores/ to game-ready loops, and the
one-shot stingers in tools/music/stingers/ to game-ready cues.

  python3 tools/music/build.py battle_border            # render one score
  python3 tools/music/build.py --all                    # render every score
  python3 tools/music/build.py battle_border --preview  # also write jump previews
  python3 tools/music/build.py --stingers levelup       # render one stinger (every key)
  python3 tools/music/build.py --stingers               # render every stinger
  python3 tools/music/build.py --prune-cache 14         # drop stems unused for 14 days

Loops go to assets/audio/music/<key>.mp3 (+ <key>_<variant>.mp3); the loop
table src/utils/musicLoops.js is rewritten from tools/music/loops.json.
Stingers go to assets/audio/stingers/; a keyed stinger is rendered once per
tonic the music uses (stinger_<name>_<tonic>.mp3) so it can play in the key
of whatever track is running. src/utils/musicStingers.js is rewritten from
tools/music/stingers.json.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from engine import palette  # noqa: E402
from engine.form import check_form  # noqa: E402
from engine.instruments import INSTRUMENTS  # noqa: E402
from engine.render import Renderer, cache_dir, prune_cache  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'assets', 'audio', 'music')
STINGER_OUT = os.path.join(ROOT, 'assets', 'audio', 'stingers')
SFX_OUT = os.path.join(ROOT, 'assets', 'audio', 'sfx')
# the file the level-up plays when its cue can't sound (see AudioManager.playStinger)
LEVELUP_FALLBACK_FROM = 'stinger_levelup_D'
PREVIEW = os.path.join(ROOT, 'References', 'music-preview')
LOOPS_JSON = os.path.join(HERE, 'loops.json')
LOOPS_JS = os.path.join(ROOT, 'src', 'utils', 'musicLoops.js')
STINGERS_JSON = os.path.join(HERE, 'stingers.json')
STINGERS_JS = os.path.join(ROOT, 'src', 'utils', 'musicStingers.js')

# Pitch classes as file-safe names. Stingers are written in D.
PITCH_CLASSES = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']
ENHARMONIC = {'C#': 'Db', 'D#': 'Eb', 'F#': 'Gb', 'G#': 'Ab', 'A#': 'Bb', 'Cb': 'B', 'Fb': 'E',
              'E#': 'F', 'B#': 'C'}


def pitch_class(tonic: str) -> str:
    pc = ENHARMONIC.get(tonic, tonic)
    if pc not in PITCH_CLASSES:
        raise ValueError(f'unknown tonic {tonic!r}')
    return pc


def offset_from_d(pc: str) -> int:
    """Semitones from D to pc, in -6..+5 so transposed stingers stay near their written range."""
    return (PITCH_CLASSES.index(pc) - 2 + 6) % 12 - 6


def list_modules(folder):
    return sorted(f[:-3] for f in os.listdir(os.path.join(HERE, folder))
                  if f.endswith('.py') and not f.startswith('_'))


def list_scores():
    return list_modules('scores')


def check_or_exit(score):
    problems = check_form(score)
    if problems:
        raise SystemExit('\n'.join(['form check failed:', *problems]))


def load_json(path):
    return json.load(open(path)) if os.path.exists(path) else {}


def save_json(path, table):
    with open(path, 'w') as f:
        json.dump(table, f, indent=2, sort_keys=True)
        f.write('\n')


def refresh_tonics(table):
    """Tonics come from the scores themselves (a cheap import, no render)."""
    by_score = {}
    for key, entry in table.items():
        name = entry.get('score')
        if not name:
            continue
        if name not in by_score:
            by_score[name] = importlib.import_module(f'scores.{name}').build().tonic
        tonic = by_score[name]
        if not tonic:
            raise SystemExit(f'score {name} declares no tonic')
        entry['tonic'] = pitch_class(tonic)


def music_tonics(table):
    return sorted({e['tonic'] for e in table.values() if e.get('tonic')},
                  key=PITCH_CLASSES.index)


def write_loops_js(table):
    lines = [
        '// Generated by tools/music/build.py from tools/music/loops.json. Do not edit.',
        '// Loop points (seconds) for the composed score: each file plays its intro once,',
        '// then loops [loopStart, loopEnd). Variants of one cue share identical timing so',
        '// the adaptive layers can crossfade sample-accurately. `duration` lets the',
        '// player reject loop points that do not belong to the decoded file. `tonic` is',
        "// the track's home key, which picks the matching version of a stinger.",
        'export const MUSIC_LOOPS = {',
    ]
    for key in sorted(table):
        e = table[key]
        lines.append(f"  {key}: {{ loopStart: {e['loopStart']}, loopEnd: {e['loopEnd']}, "
                     f"duration: {e['duration']}, tonic: '{e['tonic']}' }},")
    lines.append('};')
    lines.append('')
    with open(LOOPS_JS, 'w') as f:
        f.write('\n'.join(lines))


def write_stingers_js(stingers):
    lines = [
        '// Generated by tools/music/build.py from tools/music/stingers.json. Do not edit.',
        '// One-shot cues (assets/audio/stingers/). A keyed stinger has one file per tonic',
        '// (stinger_<name>_<tonic>) so it sounds in the key of the music under it;',
        '// `notesEnd` is when its notes stop (the rest is tail) and `duration` its length;',
        '// `handoff` (a hinge cue) is when the next track\'s first downbeat falls.',
        'export const MUSIC_STINGERS = {',
    ]
    for name in sorted(stingers):
        e = stingers[name]
        tonics = ', '.join(f"'{t}'" for t in e['tonics'])
        handoff = f", handoff: {e['handoff']}" if e.get('handoff') is not None else ''
        lines.append(f"  {name}: {{ keyed: {'true' if e['keyed'] else 'false'}, "
                     f"tonics: [{tonics}], notesEnd: {e['notesEnd']}, "
                     f"duration: {e['duration']}{handoff} }},")
    lines.append('};')
    lines.append('')
    with open(STINGERS_JS, 'w') as f:
        f.write('\n'.join(lines))


def prettier(*paths):
    """Generated JS/JSON is formatted like the rest of the repo (CI checks it)."""
    try:
        subprocess.run(['npx', 'prettier', '--write', *paths], cwd=ROOT, check=True,
                       capture_output=True)
    except (OSError, subprocess.CalledProcessError) as err:
        print(f'WARNING: prettier failed ({err}); run `npx prettier --write` on {paths}')


def build_scores(names, args, table):
    for name in names:
        t = time.time()
        mod = importlib.import_module(f'scores.{name}')
        score = mod.build()
        check_or_exit(score)
        key = getattr(mod, 'KEY', f'music_{name}')
        print(f'[{name}] -> {key}  ({score.title})')
        r = Renderer(score)
        meta = r.export(key, variants=args.variants, out_dir=None if args.no_out else OUT,
                        preview_dir=PREVIEW if args.preview else None)
        if not args.no_out:
            for k, info in meta.items():
                table[k] = {**info, 'score': name, 'title': score.title}
        print(f'[{name}] done in {time.time() - t:.1f}s')


def build_stingers(names, args, tonics, stingers):
    for name in names:
        mod = importlib.import_module(f'stingers.{name}')
        keyed = bool(getattr(mod, 'KEYED', True))
        targets = tonics if keyed else [None]
        # an unkeyed stinger may still name the key it is heard in (an act card
        # plays in its act's map key); it is written in D like the others
        fixed = getattr(mod, 'TONIC', None)
        rendered = {}
        for pc in targets:
            t = time.time()
            home = pc or (pitch_class(fixed) if fixed else None)
            score = mod.build(transpose=offset_from_d(home) if home else 0)
            if not score.one_shot:
                raise SystemExit(f'stinger {name} must be a one-shot score')
            check_or_exit(score)
            key = f'stinger_{name}_{pc}' if pc else f'stinger_{name}'
            print(f'[stinger {name}] -> {key}  ({score.title})')
            meta = Renderer(score).export(
                key, variants=['full'], out_dir=None if args.no_out else STINGER_OUT,
                preview_dir=PREVIEW if args.preview else None)
            rendered[key] = meta[key]
            if key == LEVELUP_FALLBACK_FROM and not args.no_out and STINGER_OUT != SFX_OUT:
                # the level-up's fallback sound is this cue, so it never sounds out of date
                shutil.copyfile(os.path.join(STINGER_OUT, f'{key}.mp3'),
                                os.path.join(SFX_OUT, 'sfx_levelup.mp3'))
            print(f'[stinger {name}] done in {time.time() - t:.1f}s')
        if not args.no_out:
            stingers[name] = {
                'keyed': keyed,
                'tonics': [pc for pc in targets if pc],
                'title': score.title,
                'notesEnd': max(v['notesEnd'] for v in rendered.values()),
                'duration': max(v['duration'] for v in rendered.values()),
                'files': rendered,
            }
            # a hinge cue hands over to a track on a downbeat HANDOFF_BARS bars in
            bars = getattr(mod, 'HANDOFF_BARS', None)
            if bars is not None:
                stingers[name]['handoff'] = round(score.seconds(score.bar(bars + 1)), 6)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scores', nargs='*')
    ap.add_argument('--all', action='store_true')
    ap.add_argument('--stingers', nargs='*', help='stingers to render (none listed: all)')
    ap.add_argument('--preview', action='store_true')
    ap.add_argument('--no-out', action='store_true', help='skip writing game assets')
    ap.add_argument('--variants', nargs='*')
    ap.add_argument('--palette', help='palette (default: the house palette), e.g. '
                    'lab:choir=vpo_mixed for an audition (see engine/palette.py)')
    ap.add_argument('--prune-cache', type=float, metavar='DAYS',
                    help='first delete cached stems (any score) unused for DAYS days')
    args = ap.parse_args()
    if args.palette is not None:
        palette.request(args.palette)
    if args.prune_cache is not None:
        n, freed = prune_cache(args.prune_cache)
        print(f'pruned {n} stems unused for {args.prune_cache:g} days ({freed / 1e6:.0f} MB)'
              f' from {cache_dir()}')
        if not (args.scores or args.all or args.stingers is not None):
            return
    audition = palette.is_audition(palette.requested())
    if audition:
        # an audition never touches the game's assets or loop tables
        global OUT, STINGER_OUT, PREVIEW
        lab_out = os.path.join(palette.lab_dir(), 'out')
        OUT, STINGER_OUT, PREVIEW = lab_out, lab_out, os.path.join(lab_out, 'preview')
        palette.apply(palette.parse(palette.requested()), INSTRUMENTS)
        print(palette.describe(), '-> writing to', lab_out)

    table = load_json(LOOPS_JSON)
    names = list_scores() if args.all else args.scores
    build_scores(names, args, table)
    refresh_tonics(table)

    stingers = load_json(STINGERS_JSON)
    if args.stingers is not None:
        chosen = args.stingers or list_modules('stingers')
        build_stingers(chosen, args, music_tonics(table), stingers)

    if not args.no_out and not audition:
        save_json(LOOPS_JSON, table)
        write_loops_js(table)
        # every keyed stinger must cover every key the music uses
        missing = {n: sorted(set(music_tonics(table)) - set(e['tonics']))
                   for n, e in stingers.items() if e['keyed']}
        missing = {n: m for n, m in missing.items() if m}
        if missing:
            print(f'WARNING: keyed stingers missing tonics (re-render them): {missing}')
        save_json(STINGERS_JSON, stingers)
        write_stingers_js(stingers)
        prettier(LOOPS_JSON, LOOPS_JS, STINGERS_JSON, STINGERS_JS)


if __name__ == '__main__':
    main()
