// Generated by tools/music/build.py from tools/music/stingers.json. Do not edit.
// One-shot cues (assets/audio/stingers/). A keyed stinger has one file per tonic
// (stinger_<name>_<tonic>) so it sounds in the key of the music under it;
// `notesEnd` is when its notes stop (the rest is tail) and `duration` its length;
// `handoff` (a hinge cue) is when the next track's first downbeat falls.
export const MUSIC_STINGERS = {
  act_card_act1: { keyed: false, tonics: [], notesEnd: 5.0, duration: 6.962 },
  act_card_act2: { keyed: false, tonics: [], notesEnd: 4.8, duration: 5.933 },
  act_card_act3: { keyed: false, tonics: [], notesEnd: 6.0, duration: 8.187 },
  act_card_act4: { keyed: false, tonics: [], notesEnd: 6.667, duration: 9.722 },
  act_card_finalBoss: { keyed: false, tonics: [], notesEnd: 8.0, duration: 11.247 },
  arrival: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.0,
    duration: 3.579,
  },
  boss_archmage: { keyed: false, tonics: [], notesEnd: 4.138, duration: 6.016 },
  boss_berserker_king: { keyed: false, tonics: [], notesEnd: 3.429, duration: 5.358 },
  boss_blade_lord: { keyed: false, tonics: [], notesEnd: 4.0, duration: 5.479 },
  boss_card: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 4.286,
    duration: 5.938,
  },
  boss_dark_rider: { keyed: false, tonics: [], notesEnd: 3.81, duration: 5.115 },
  boss_emperor_card: { keyed: false, tonics: [], notesEnd: 4.615, duration: 6.421 },
  boss_felled: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.5,
    duration: 4.873,
  },
  boss_iron_captain: { keyed: false, tonics: [], notesEnd: 4.138, duration: 5.001 },
  boss_iron_wall: { keyed: false, tonics: [], notesEnd: 5.0, duration: 6.663 },
  boss_knight_commander: { keyed: false, tonics: [], notesEnd: 3.636, duration: 5.71 },
  boss_lieutenant_card: { keyed: false, tonics: [], notesEnd: 4.8, duration: 5.927 },
  boss_warchief: { keyed: false, tonics: [], notesEnd: 4.0, duration: 6.04 },
  deed: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 1.875,
    duration: 5.757,
  },
  eclipse: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.636,
    duration: 6.765,
  },
  entity_answer: { keyed: false, tonics: [], notesEnd: 3.529, duration: 5.031, handoff: 3.529412 },
  levelup: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 1.818,
    duration: 4.489,
  },
  levelup_blank: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 0.909,
    duration: 3.221,
  },
  levelup_perfect: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.636,
    duration: 5.588,
  },
  lord_fallen: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.333,
    duration: 5.201,
  },
  promotion_crown: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 4.545,
    duration: 7.318,
  },
  promotion_gather: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.0,
    duration: 4.624,
  },
  recruit: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.6,
    duration: 6.553,
  },
  rewind: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.4,
    duration: 4.498,
  },
  sealed: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.0,
    duration: 4.254,
  },
};
