// musicConfig.js — Centralized music track configuration
//
// Every track is an original composition rendered from tools/music/scores/
// (see tools/music/SCORE.md). Loop points live in musicLoops.js, generated by
// the same build.

import { MUSIC_LOOPS } from './musicLoops.js';

export const MUSIC = {
  title: 'music_title',
  homeBase: 'music_home_base',

  nodeMap: {
    act1: 'music_explore_act1',
    act2: 'music_explore_act2',
    act3: 'music_explore_act3',
    act4: 'music_explore_act4',
    // the Deep: Act I's loom with its notes taken away
    finalBoss: 'music_explore_deep',
  },

  battle: {
    act1: ['music_battle_act1', 'music_battle_act1_2'],
    act2: ['music_battle_act2', 'music_battle_act2_2'],
    act3: ['music_battle_act3', 'music_battle_act3_2'],
    act4: ['music_battle_act4', 'music_battle_act2'],
    finalBoss: ['music_battle_act4'],
  },

  boss: {
    act1: 'music_boss_act1',
    act2: 'music_boss_act2',
    act3: 'music_boss_act3',
    act4: 'music_boss_emperor',
    finalBoss: 'music_boss_lieutenant',
  },

  // The story's antagonists get their own themes wherever they are fought.
  bossByName: {
    'The Lieutenant': 'music_boss_lieutenant',
    'The Emperor': 'music_boss_emperor',
    'The Entity': 'music_boss_entity',
  },

  // Escape maps (get out before the dark closes) have their own pursuit theme.
  escape: 'music_battle_escape',
  colosseum: 'music_colosseum',
  // Choosing blessings at the start of a run.
  shrine: 'music_shrine',
  shop: 'music_shop',
  rest: 'music_rest',
  victory: 'music_victory',
  defeat: 'music_defeat',
  runWin: 'music_run_win',
  loot: 'music_loot',
};

// Adaptive battle themes: each has a calm ("rain") mix on the same timeline as
// the full ("thunder") mix, so the game can crossfade between them mid-loop.
export const MUSIC_LAYERS = {
  music_battle_act1: { calm: 'music_battle_act1_calm' },
  music_battle_act1_2: { calm: 'music_battle_act1_2_calm' },
  music_battle_act2: { calm: 'music_battle_act2_calm' },
  music_battle_act2_2: { calm: 'music_battle_act2_2_calm' },
  music_battle_act3: { calm: 'music_battle_act3_calm' },
  music_battle_act3_2: { calm: 'music_battle_act3_2_calm' },
  music_battle_act4: { calm: 'music_battle_act4_calm' },
  music_battle_escape: { calm: 'music_battle_escape_calm' },
};

// Each boss's encounter card plays its own motif (tools/music/stingers/boss_*).
// The Entity's card is a hole in the music instead (null); an unlisted boss
// gets the generic card cue.
export const BOSS_CARD_CUES = {
  'Iron Captain': 'boss_iron_captain',
  Warchief: 'boss_warchief',
  'Knight Commander': 'boss_knight_commander',
  Archmage: 'boss_archmage',
  'Dark Rider': 'boss_dark_rider',
  'Blade Lord': 'boss_blade_lord',
  'Iron Wall': 'boss_iron_wall',
  'Berserker King': 'boss_berserker_king',
  'The Emperor': 'boss_emperor_card',
  'The Lieutenant': 'boss_lieutenant_card',
  'The Entity': null,
};

// Stingers decoded ahead whenever a track starts (in that track's key): the
// cues that can fire at any moment of a battle. Rarer ones load on demand.
export const STINGER_PRELOAD = ['levelup', 'levelup_perfect', 'levelup_blank', 'sealed', 'deed'];

/** Layer name -> music key for an adaptive track (null for single-layer tracks). */
export function getMusicLayers(key) {
  const extra = MUSIC_LAYERS[key];
  if (!extra) return null;
  return { full: key, ...extra };
}

/** Loop points ({ loopStart, loopEnd, duration } in seconds) for a music key. */
export function getMusicLoop(key) {
  return MUSIC_LOOPS[key] || null;
}

/** Pick a random element from an array, or return the value if it's a string. */
export function pickTrack(pool) {
  if (typeof pool === 'string') return pool;
  if (Array.isArray(pool)) return pool[Math.floor(Math.random() * pool.length)];
  return pool;
}

function resolveActMusicPool(entry, act) {
  if (!entry || typeof entry !== 'object') return undefined;
  const orderedActs = [];
  if (typeof act === 'string' && act.trim().length > 0) orderedActs.push(act);
  for (const fallbackAct of ['act4', 'act3', 'act2', 'act1', 'finalBoss']) {
    if (!orderedActs.includes(fallbackAct)) orderedActs.push(fallbackAct);
  }
  for (const key of orderedActs) {
    const candidate = entry[key];
    if (candidate !== undefined && candidate !== null) return candidate;
  }
  const firstDefined = Object.values(entry).find((value) => value !== undefined && value !== null);
  return firstDefined;
}

/** Get the correct music key for a purpose + act. */
export function getMusicKey(purpose, act) {
  const entry = MUSIC[purpose];
  if (typeof entry === 'string') return entry;
  if (entry && typeof entry === 'object') {
    const actEntry = resolveActMusicPool(entry, act);
    const picked = pickTrack(actEntry);
    return picked || MUSIC.title;
  }
  return entry || MUSIC.title;
}

/** Boss battle music: a named antagonist's own theme, else the act's boss theme. */
export function getBossMusicKey(bossName, act) {
  if (typeof bossName === 'string' && MUSIC.bossByName[bossName]) {
    return MUSIC.bossByName[bossName];
  }
  return getMusicKey('boss', act);
}

/**
 * The enrage layer a boss adds to the theme playing (null when that theme has
 * none for this boss). Layers are rendered as `<theme>_enrage_<boss>`:
 * 'Iron Captain' -> 'iron_captain', 'The Emperor' -> 'emperor'.
 */
export function getBossEnrageLayer(themeKey, bossName) {
  if (!themeKey || typeof bossName !== 'string' || !bossName) return null;
  const slug = bossName
    .replace(/^the\s+/i, '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_');
  const key = `${themeKey}_enrage_${slug}`;
  return MUSIC_LOOPS[key] ? key : null;
}
