// Generated by tools/music/build.py from tools/music/stingers.json. Do not edit.
// One-shot cues (assets/audio/stingers/). A keyed stinger has one file per tonic
// (stinger_<name>_<tonic>) so it sounds in the key of the music under it;
// `notesEnd` is when its notes stop (the rest is tail) and `duration` its length;
// `handoff` (a hinge cue) is when the next track's first downbeat falls.
export const MUSIC_STINGERS = {
  act_card_act1: { keyed: false, tonics: [], notesEnd: 5.0, duration: 6.921 },
  act_card_act2: { keyed: false, tonics: [], notesEnd: 4.8, duration: 5.952 },
  act_card_act3: { keyed: false, tonics: [], notesEnd: 6.0, duration: 7.924 },
  act_card_act4: { keyed: false, tonics: [], notesEnd: 6.667, duration: 9.722 },
  act_card_finalBoss: { keyed: false, tonics: [], notesEnd: 8.0, duration: 11.26 },
  arrival: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.0,
    duration: 3.539,
  },
  boss_archmage: { keyed: false, tonics: [], notesEnd: 4.138, duration: 6.137 },
  boss_berserker_king: { keyed: false, tonics: [], notesEnd: 3.429, duration: 5.253 },
  boss_blade_lord: { keyed: false, tonics: [], notesEnd: 4.0, duration: 5.616 },
  boss_card: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 4.286,
    duration: 5.904,
  },
  boss_dark_rider: { keyed: false, tonics: [], notesEnd: 3.81, duration: 5.131 },
  boss_emperor_card: { keyed: false, tonics: [], notesEnd: 4.615, duration: 6.387 },
  boss_felled: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.5,
    duration: 4.884,
  },
  boss_iron_captain: { keyed: false, tonics: [], notesEnd: 4.138, duration: 4.962 },
  boss_iron_wall: { keyed: false, tonics: [], notesEnd: 5.0, duration: 6.588 },
  boss_knight_commander: { keyed: false, tonics: [], notesEnd: 3.636, duration: 5.165 },
  boss_lieutenant_card: { keyed: false, tonics: [], notesEnd: 4.8, duration: 6.281 },
  boss_warchief: { keyed: false, tonics: [], notesEnd: 4.0, duration: 5.861 },
  deed: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 1.875,
    duration: 5.719,
  },
  eclipse: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.636,
    duration: 6.742,
  },
  entity_answer: { keyed: false, tonics: [], notesEnd: 3.529, duration: 4.799, handoff: 3.529412 },
  levelup: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 1.818,
    duration: 4.414,
  },
  levelup_blank: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 0.909,
    duration: 3.221,
  },
  levelup_perfect: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.636,
    duration: 5.488,
  },
  lord_fallen: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.333,
    duration: 5.074,
  },
  promotion_crown: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 4.545,
    duration: 7.527,
  },
  promotion_gather: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.0,
    duration: 4.67,
  },
  recruit: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 3.6,
    duration: 6.537,
  },
  rewind: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.4,
    duration: 4.526,
  },
  sealed: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 2.0,
    duration: 4.2,
  },
};
