// Generated by tools/music/build.py from tools/music/stingers.json. Do not edit.
// One-shot cues (assets/audio/stingers/). A keyed stinger has one file per tonic
// (stinger_<name>_<tonic>) so it sounds in the key of the music under it;
// `notesEnd` is when its notes stop (the rest is tail) and `duration` its length.
export const MUSIC_STINGERS = {
  levelup: {
    keyed: true,
    tonics: ['C', 'Db', 'D', 'E', 'F', 'G', 'A', 'Bb', 'B'],
    notesEnd: 1.818,
    duration: 5.885,
  },
};
