// Single palette source for DOM and Phaser. Commit the CSS so standalone imports work.
import fs from 'node:fs';
const source = new URL('../src/ui/uiPalette.json', import.meta.url);
const output = new URL('../src/ui/uiTokens.css', import.meta.url);
const palette = JSON.parse(fs.readFileSync(source, 'utf8'));
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const css =
  '/* Generated by tools/buildUITheme.js from uiPalette.json. */\n:root {\n' +
  Object.entries(palette)
    .map(([key, value]) => `  --re-${kebab(key)}: ${value};`)
    .join('\n') +
  '\n}\n';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(output, 'utf8') !== css) throw new Error('UI token CSS is stale');
} else fs.writeFileSync(output, css);
