import { DOM_UI_DEPTHS } from '../src/utils/uiDepths.js';
// Single palette source for DOM and Phaser. Commit the CSS so standalone imports work.
import fs from 'node:fs';
const source = new URL('../src/ui/uiPalette.json', import.meta.url);
const output = new URL('../src/ui/uiTokens.css', import.meta.url);
const palette = JSON.parse(fs.readFileSync(source, 'utf8'));
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const css =
  '/* Generated by tools/buildUITheme.js from uiPalette.json. */\n:root {\n' +
  Object.entries(palette)
    .map(([key, value]) => `  --re-${kebab(key)}: ${value};`)
    .join('\n') +
  '\n}\n';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(output, 'utf8') !== css) throw new Error('UI token CSS is stale');
} else fs.writeFileSync(output, css);

const depthsOutput = new URL('../src/ui/uiDepthTokens.css', import.meta.url);
const depthsCss =
  '/* Generated from src/utils/uiDepths.js. */\n:root {\n' +
  Object.entries(DOM_UI_DEPTHS)
    .map(([key, value]) => `  --re-depth-${key.toLowerCase()}: ${value};`)
    .join('\n') +
  '\n}\n';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(depthsOutput, 'utf8') !== depthsCss)
    throw new Error('DOM depth CSS is stale');
  const directory = new URL('../src/ui/', import.meta.url);
  for (const name of fs.readdirSync(directory).filter((name) => name.endsWith('.css'))) {
    const text = fs.readFileSync(new URL(name, directory), 'utf8');
    for (const match of text.matchAll(/z-index\s*:\s*([^;{}]+)/g)) {
      if (/\b\d+\b/.test(match[1])) throw new Error(`Raw DOM depth in ${name}: ${match[0]}`);
    }
  }
} else fs.writeFileSync(depthsOutput, depthsCss);
